version: 2

project_name: dlna115

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/main
    binary: dlna115
    ldflags:
      - -s -w
      - -X github.com/deadblue/dlna115/pkg/version.version={{.Version}}
    tags:
      - netgo
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_amd64_v3
      - linux_arm_7
      - linux_arm64
      - windows_amd64
      - windows_amd64_v3
      - windows_arm64

archives:
  - format: zip
    files:
      - src: "assets/config.yaml"
        strip_parent: true
      - src: "assets/config-quickstart.yaml"
        strip_parent: true

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  prerelease: auto
  mode: keep-existing

changelog:
  disable: true
