# 115 storage settings
storage:

  # Source to get 115 credential.
  credential-source:
    # Credential source type: "file" or "url"
    type: "file"
    # For "file" type, source should be full path of the file.
    # For "url" type, source should be the URL.
    source: "/path/to/credential.txt"
    # Secret key to decrypt credential.
    secret: ""

  # Top folders which will be shown under root directory.
  top-folders:

    # A virtual folder which contains stared files.
    - type: "star"
      # You can set name to override default name.
      name: "Favorites"

    # A virtual folder which contains files with given label.
    - type: "label"
      # Target must be set, and should be a label name.
      target: "label-name"
      # Default value is the label name.
      name: ""

    # A directory on storage.
    - type: "dir"
      # Target must be set, and should be a the directory path.
      target: "parent/child1/child2"
      # Default value is the base name of directory.
      name: ""

  # Do not use HLS for video.
  # Set this to true if you UPnP player does not support HLS.
  disable-hls: false

# Media server settings
media:
  # Listening port, default value is 8115.
  port: 8115
  # Unique ID, server will automatically generate one if you do not set.
  uuid: ""
  # Server friendly name, default value is "115"
  name: ""
