name: mkdocs

on:
  push:
    branches: 
      - docs

permissions:
  contents: write

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: pip install mkdocs-material

      - run: mkdocs gh-deploy --force
